# Generated by Django 2.2.28 on 2025-07-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0177_testcase_result_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sessions',
            field=models.IntegerField(default=0, help_text='Number of times this user has logged in to the site.', verbose_name='number of sessions'),
        ),
    ]
