# Generated by Django 2.2.28 on 2025-08-08 09:32

import django.core.validators
from django.db import migrations, models
import judge.models.profile


def update_zero_to_null(apps, schema_editor):
    Profile = apps.get_model('judge', 'Profile')
    Profile.objects.filter(sessions=0).update(sessions=None)


def update_null_to_zero(apps, schema_editor):
    Profile = apps.get_model('judge', 'Profile')
    Profile.objects.filter(sessions__isnull=True).update(sessions=0)


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0178_max_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sessions',
            field=models.IntegerField(help_text='Number of times this user has logged in to the site.', null=True, verbose_name='number of sessions'),
        ),

        migrations.RunPython(update_zero_to_null, update_null_to_zero),
    ]
