# Generated by Django 3.2.20 on 2023-08-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0192_add_contest_tag_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualJudge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='virtual_judge',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_virtual_judged',
            field=models.BooleanField(default=False),
        ),
    ]
