# Generated by Django 3.2.23 on 2024-06-07 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0193_add_enable_grading'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagdata',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tagdata',
            name='assigner',
        ),
        migrations.RemoveField(
            model_name='tagdata',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='tagdata',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tagproblem',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='allow_tagging',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='TagData',
        ),
        migrations.DeleteModel(
            name='TagGroup',
        ),
        migrations.DeleteModel(
            name='TagProblem',
        ),
    ]
