# Generated by Django 3.2.23 on 2024-04-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0193_add_enable_grading'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='affiliation',
            field=models.CharField(blank=True, help_text='Affiliation name shown in ranking', max_length=100, verbose_name='affiliation'),
        ),
    ]
